### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by joaom182** [jarradseers/express-load#37]
Hello, i have the following error

``` bash
TypeError: Arguments to path.join must be strings
      at Object.posix.join (path.js:467:13)
      at Context.<anonymous> (test/rank/rankServiceTest.js:19:3)
```

with the following code

``` javascript
var Q = require('q');
var async = require('async');
var expect = require('expect.js');
var load = require('express-load');
var app = require('../../app.js');
var mongoose = require('mongoose');
var basicMongoDbMock = require('../mockDb/basicMongoDbMock');

describe('Suite 01', function () {

	before(function (done) {
		this.timeout(8000);

		load('config') //  at Context.<anonymous> (test/rank/rankServiceTest.js:19:3)
			.then('enums')
			.then('models/UniqueId.js')
			.then('models')
			.then('modules/rank')
			.into(app, function () {
			});
	});

	beforeEach(function (done) {
		mongoose.connect('mongodb://localhost:27017/squid_test');

		basicMongoDbMock
			.seed(Mission, Participation, User, Image)
			.then(function () {
				done();
			});
	});

	afterEach(function (done) {
		basicMongoDbMock
			.unseed(Mission, Participation, User, Image)
			.then(function () {
				mongoose.disconnect(function () {
					done();
				});
			});
	});

	it('Should...', function (done) {
		
	});

});
```

This is the start line of the exception
```
		load('config') //  at Context.<anonymous> (test/rank/rankServiceTest.js:19:3)
```

Have any idea of the cause for the error?

**Comment by joaom182** [comment]
I found the error! :)

Look my inspection on code:

![express-load](https://cloud.githubusercontent.com/assets/3612098/7335538/242cbb7e-eb9e-11e4-9425-3681e432fb56.png)

`for in` is reading the prototype chain properties, not only own properties. I can create a pull request to fix this?
